# Generated by Django 5.1.2 on 2025-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_livro_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(blank=True, related_name="livros", to="core.autor"),
        ),
    ]
