# Generated by Django 5.1.2 on 2025-05-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_livro_autor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor",
            new_name="autores",
        ),
    ]
